### ISSUE TITLE
Inlined JAR cannot be loaded (ReflectionException; Relative path in absolute URI)

### ISSUE THREAD

**Issue by myron0815** [OpenPojo/openpojo#118]
Having some OSGI bundles, which add additional JARs from inlined /lib/ folder to classpath (referenced in manifest) But when OpenPojo tries to load them, the URI seems wrongly constructed:

```
com.openpojo.reflection.exception.ReflectionException: Relative path in absolute URI: file://:/Users/myron/workspace/project/libs/additional.jar!/com/mycompany/myClass.class
	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.impl.PojoClassImpl.getSourcePath(PojoClassImpl.java:195)
	at com.mycompany.PojoTester$MyFilter.include(PojoTester.java:41)
	at com.openpojo.reflection.filters.FilterChain.include(FilterChain.java:46)
	at com.openpojo.reflection.impl.PojoPackageImpl.getPojoClasses(PojoPackageImpl.java:81)
	at com.openpojo.reflection.service.impl.DefaultPojoClassLookupService.getPojoClassesRecursively(DefaultPojoClassLookupService.java:99)
	at com.openpojo.reflection.impl.PojoClassFactory.getPojoClassesRecursively(PojoClassFactory.java:81)
	at com.mycompany.PojoTester.testPojoStructureAndBehavior(PojoTester.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: com.openpojo.reflection.exception.ReflectionException: Relative path in absolute URI: file://:/Users/myron/workspace/project/libs/additional.jar!/com/mycompany/myClass.class
	at com.openpojo.reflection.exception.ReflectionException.getInstance(ReflectionException.java:51)
	at com.openpojo.reflection.java.packageloader.impl.URLToFileSystemAdapter.getAsURI(URLToFileSystemAdapter.java:79)
	at com.openpojo.reflection.impl.PojoClassImpl.getSourcePath(PojoClassImpl.java:193)
	... 29 more
Caused by: java.net.URISyntaxException: Relative path in absolute URI: file://:/Users/myron/workspace/project/libs/additional.jar!/com/mycompany/myClass.class
	at java.net.URI.checkPath(URI.java:1823)
	at java.net.URI.<init>(URI.java:672)
	at com.openpojo.reflection.java.packageloader.impl.URLToFileSystemAdapter.getAsURI(URLToFileSystemAdapter.java:77)
	... 30 more
```

As you can see, the file:// is missing an additional slash (but the drive letter C is being removed)
Kinda same on our linux buildserver:

```
com.openpojo.reflection.java.packageloader.env.JavaClassPathClassLoader - Loading classes from: /data/jenkins/.m2/repository/p2/osgi/bundle/com.mycompany.commontypes/1.0.0.201806131312/com.mycompany.commontypes-1.0.0.201806131312.jar
com.openpojo.reflection.exception.ReflectionException: Relative path in absolute URI: file://ata/jenkins/.m2/repository/p2/osgi/bundle/com.mycompany.commontypes/1.0.0.201806131312/com.mycompany.commontypes-1.0.0.201806131312.jar!/com/mycompany/commontypes/Orientation.class
```

See attached SSCCE for reproduction

**Comment by myron0815** [comment]
[SSCCE_118.zip](https://github.com/OpenPojo/openpojo/files/2145122/SSCCE_118.zip)

**Comment by max-norris** [comment]
Just ran into this same problem on only one of our projects (out of 20).  I was not able to isolate what the change was that was causing it, but from debugging it just seems that JAR files were showing **file:** instead of **file://**

**Comment by max-norris** [comment]
Sure, no problem, I'll get those added probably later tonight.

**Comment by oshoukry** [comment]
First off, I'd like to thank you both very much for the code sample, and the work to fix it.
@max-norris your fix has been included in the latest main branch and will be released shortly.
@myron0815 the fix addresses this issue indeed.
