### ISSUE TITLE
Hard dependency on JVM implementation-specific classes

### ISSUE THREAD

**Issue by boonware** [OpenPojo/openpojo#130]
The project has a hard dependency on JVM implementation-specific classes. For example, running on an IBM J9 JVM the following is observed:

```
java.lang.NoClassDefFoundError: sun.security.krb5.Credentials
	at com.openpojo.random.generator.security.CredentialsRandomGenerator.<clinit>(CredentialsRandomGenerator.java:39)
	at com.openpojo.registry.ServiceRegistrar.initializeRandomGeneratorService(ServiceRegistrar.java:94)
	at com.openpojo.registry.ServiceRegistrar.<init>(ServiceRegistrar.java:57)
	at com.openpojo.registry.ServiceRegistrar.<init>(ServiceRegistrar.java:49)
	at com.openpojo.registry.ServiceRegistrar$Instance.<clinit>(ServiceRegistrar.java:199)
	at com.openpojo.registry.ServiceRegistrar.getInstance(ServiceRegistrar.java:170)
	at com.openpojo.reflection.impl.PojoClassFactory.getPojoClass(PojoClassFactory.java:42)
        ...
```

Related: https://github.com/OpenPojo/openpojo/issues/84

**Comment by cvikram21** [comment]
When will this fix be released?

**Comment by oshoukry** [comment]
Thank you for your interest in OpenPojo.
Release 0.8.13 is now out.

**Comment by cvikram21** [comment]
0.8.13 fixed the issue. Thanks.

**Comment by oshoukry** [comment]
Thank you for confirming!
Please feel free to submit any issues for improvements or bugs anytime.
