### ISSUE TITLE
NullPointerException with ASMDetector

### ISSUE THREAD

**Issue by evernat** [OpenPojo/openpojo#133]
With the attached [test project](https://github.com/OpenPojo/openpojo/files/3482641/Test.zip), I get the following NPE :
```java
java.lang.ExceptionInInitializerError
        at com.openpojo.reflection.construct.InstanceFactory.wrapAbstractClass(InstanceFactory.java:107)
        at com.openpojo.reflection.construct.InstanceFactory.getInstance(InstanceFactory.java:74)
        at com.openpojo.reflection.construct.InstanceFactory.getLeastCompleteInstance(InstanceFactory.java:103)
        at com.openpojo.random.impl.DefaultRandomGenerator.doGenerate(DefaultRandomGenerator.java:63)
        at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:99)
        at com.openpojo.random.RandomFactory.getRandomValue(RandomFactory.java:107)
        at com.openpojo.validation.test.impl.SetterTester.run(SetterTester.java:45)
        at com.openpojo.validation.utils.ValidationHelper.runValidation(ValidationHelper.java:102)
        at com.openpojo.validation.impl.DefaultValidator.validate(DefaultValidator.java:46)
        at p.TestPojo.testPojoStructureAndBehavior(TestPojo.java:72)
        at ...
Caused by: java.lang.NullPointerException
        at com.openpojo.reflection.service.impl.DefaultPojoClassLookupService.getPojoClass(DefaultPojoClassLookupService.java:64)
        at com.openpojo.reflection.impl.PojoClassFactory.getPojoClass(PojoClassFactory.java:42)
        at com.openpojo.reflection.java.bytecode.asm.ASMDetector.getBundleVersion(ASMDetector.java:58)
        at com.openpojo.reflection.java.bytecode.asm.ASMDetector.getVersion(ASMDetector.java:52)
        at com.openpojo.reflection.java.bytecode.ByteCodeFactory.<clinit>(ByteCodeFactory.java:42)
        ... 40 more
```

It is reproduced with openpojo 0.8.11 and 0.8.12.
I think it is caused by ff51b7d41b9204f4d005e8c03577956376f85c87 followed by a64e1c0cf0f7528df31bc174533b9d5e30dc90be.
And I don't think that asm version is really needed when asm is not found.

**Comment by oshoukry** [comment]
Thank you evernat for reporting this issue.

**Comment by roelver** [comment]
I ran into this same error. Debugging revealed that the ASMDetector.getVersion() could not instantiate org.objectweb.asm.ClassWriter. I added a the asm dependency to my project with a test scope. OpenPojo assumes this dependency as provided.

```
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>7.1</version>
            <scope>test</scope>
        </dependency>

```

**Comment by oshoukry** [comment]
Issue fixed, please see latest release
